from src.core.criteria import criteria_set_stem
"""
Figure Reviewer: answers a question about figures by loading page images
and querying a multimodal agent for each page.
"""

import base64
import re
from pathlib import Path
from typing import List, Optional

from src.review_workflow.engine.base import BaseComponent
from src.review_workflow.engine.utils import load_model_from_provider
from src.review_workflow.engine.token_usage import add as token_usage_add
from src.core.providers import resolve_provider_config
from strands import Agent, tool


def slug(name: str) -> str:
    return name.strip().replace(" ", "_").lower() or "process"


def get_project_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent.parent.parent.parent


class FigureReviewer(BaseComponent):
    def as_tool(
        self,
        collection_name: str,
        review_process_name: str,
        checklist_name: str,
        paper_name: str,
        log_callback=None,
        token_usage_accumulator=None,
        collections_root: Optional[Path] = None,
    ):
        # Use component id as tool name so process prompts can reference figure_reviewer
        @tool(name="figure_reviewer")
        def review_figures(question: str, page_numbers: Optional[List[int]] = None) -> str:
            """
            Analyze and answer detailed questions about figures within a paper by examining rendered page images (PNG).

            Use this tool when you need information about the content, quality, or characteristics of figures, tables, or visual elements present in the paper. The tool loads images of the specified pages and employs an AI agent to respond using vision.

            Typical use cases include:
                - Summarizing the content of figures on specific pages
                - Assessing the clarity or readability of visual elements
                - Identifying the presence, labeling, or types of figures shown
                - Comparing figures across pages
                - Positioning figures on a page

            Notes:
                - Only figures visible on the indicated pages are considered; textual content is not analyzed unless it appears in the figure image itself.
                - If page_numbers is omitted or empty, all available page images under paper_pages are used (subject to max_auto_review_pages in tool config).
                - Prefer passing explicit pages when the paper cites them (e.g. \"Figure 2\", \"page 7\").

            Args:
                question: The question you want to answer about the figures (e.g. \"What type of chart is shown on page 2?\", \"Are all axes labeled and legible?\").
                page_numbers: Optional 1-based page numbers to review (e.g. [1, 3, 5]). Omit or pass [] to auto-scan available page PNGs.

            Returns:
                A detailed answer generated by a multimodal agent, describing the figures on the provided pages in response to the input question.
            """
            return self.execute_tool(
                question=question,
                collection_name=collection_name,
                review_process_name=review_process_name,
                checklist_name=checklist_name,
                paper_name=paper_name,
                page_numbers=page_numbers,
                log_callback=log_callback,
                token_usage_accumulator=token_usage_accumulator,
                collections_root=collections_root,
            )

        return review_figures

    def _paper_pages_dir(
        self,
        collection_name: str,
        review_process_name: str,
        checklist_name: str,
        paper_name: str,
        collections_root: Optional[Path] = None,
    ) -> Path:
        if collections_root is None:
            root = get_project_root()
            collections_root = root / "workspaces" / "guest" / "collections"
            
        checklist_clean = criteria_set_stem(checklist_name)
        return (
            Path(collections_root)
            / slug(collection_name)
            / "review_processes"
            / slug(review_process_name)
            / slug(checklist_clean)
            / paper_name
            / "paper_pages"
        )

    def _available_page_numbers_from_dir(self, pages_dir: Path) -> List[int]:
        nums: List[int] = []
        for p in pages_dir.glob("page_*.png"):
            m = re.match(r"page_(\d+)\.png$", p.name)
            if m:
                nums.append(int(m.group(1)))
        return sorted(nums)

    def execute_tool(
        self,
        question: str,
        collection_name: str,
        review_process_name: str,
        checklist_name: str,
        paper_name: str,
        page_numbers: Optional[List[int]] = None,
        log_callback=None,
        token_usage_accumulator=None,
        collections_root: Optional[Path] = None,
    ) -> str:
        def get_provider_config(provider_id: str):
            return resolve_provider_config(provider_id)

        def create_agent() -> Agent:
            provider_id = self.config.get("provider_id")
            if not provider_id:
                raise ValueError("No provider_id configured for FigureReviewer")
            provider_config = get_provider_config(provider_id)
            model = load_model_from_provider(provider_config)
            system_prompt = (
                "You are an expert at analyzing figures and images in academic papers. "
                "Answer the question based only on the provided figure/page image. Be concise and precise."
            )
            return Agent(model=model, system_prompt=system_prompt)

        pages_dir = self._paper_pages_dir(
            collection_name, review_process_name, checklist_name, paper_name, collections_root
        )
        if not pages_dir.exists():
            return (
                f"No paper_pages folder found at {pages_dir}. "
                "Enable 'Extract Pages as Image' in the Paper Loader to generate page images."
            )

        resolved = (
            sorted(set(page_numbers))
            if page_numbers
            else self._available_page_numbers_from_dir(pages_dir)
        )
        if not resolved:
            return (
                f"No page PNGs found under {pages_dir}. "
                "Enable 'Extract Pages as Image' on the Paper Loader and re-run paper loading."
            )

        max_auto = int(self.config.get("max_auto_review_pages", 24))
        if not page_numbers and len(resolved) > max_auto:
            if log_callback:
                log_callback(
                    f"figure_reviewer: scanning first {max_auto} of {len(resolved)} pages with images "
                    f"(configure max_auto_review_pages or pass explicit page_numbers for more)",
                    "warning",
                )
            resolved = resolved[:max_auto]

        if log_callback:
            log_callback(
                f"Reviewing figures for pages {resolved}",
                "info",
            )

        agent = create_agent()
        parts: List[str] = []

        for page_num in resolved:
            image_path = pages_dir / f"page_{page_num}.png"
            if not image_path.exists():
                parts.append(f"[Page {page_num}]: Image not found ({image_path.name}).")
                continue
            try:
                image_bytes_b64 = base64.b64encode(
                    image_path.read_bytes()
                ).decode("utf-8")
            except Exception as e:
                parts.append(f"[Page {page_num}]: Failed to read image: {e}.")
                continue

            message = [
                {
                    "role": "user",
                    "content": [
                        {"text": question},
                        {
                            "image": {
                                "format": "png",
                                "source": {"bytes": image_bytes_b64},
                            }
                        },
                    ],
                }
            ]
            try:
                response = agent(message)
                text = response.text if hasattr(response, "text") else str(response)
                if token_usage_accumulator is not None:
                    token_usage_add(token_usage_accumulator, response, agent)
                parts.append(f"[Page {page_num}]: {text.strip()}")
            except Exception as e:
                parts.append(f"[Page {page_num}]: Error: {e}.")

        return "\n\n".join(parts) if parts else "No pages could be reviewed."


if __name__ == "__main__":
    config = {
        "provider_id": "84efb965-d2a9-4947-9a9f-63b352b5c334",
    }
    figure_reviewer = FigureReviewer(config=config)
    figure_reviewer.execute_tool(
        question="Are all figures positioned on top of the screen?",
        collection_name="test",
        review_process_name="Demo Review Process",
        checklist_name="demo_checklist",
        paper_name="Multipole Graph Neural Operator for Parametric Partial Differential Equations.pdf",
        page_numbers=[3, 5, 7],
    )